config/routes.rb
Rails.application.routes.draw do
  get "home" => "app#welcome"

  resources :photos, only: [:index, :show, :new, :create, :destroy]
  resources :users, only: [:index, :show]
end

app/models/concerns/user_extras.rb
module UserExtras
  extend ActiveSupport::Concern

  included do
    has_many_attached :photos
  end
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  before_action :authenticate_user!

  layout "application"

  def welcome
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :destroy]

  def index
    user = User.find(params[:user]) || current_user
    @photos = user.photos.order(created_at: :desc)
  end

  def show
  end

  def new
  end

  def create
    current_user.photos.attach(params[:photo])
  end

  def destroy
    @photo.purge
    flash[:success] = "Photo deleted"
    redirect_to home_url
  end

  private

  def set_photo
    @photo = ActiveStorage::Attachment.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.where.not(id: current_user.id)
  end

  def show
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/app/_flash.html.haml
- flash.each do |name, msg|
  :javascript
    M.toast({html: "#{msg}"})

app/views/app/_nav-links.html.haml
- if current_user
  %li= link_to "Browse all", users_url
  - if current_user.admin?
    %li= link_to "Admin", "/admin"
  %li= button_to "Sign out", destroy_user_session_url, method: 'delete'
- else
  %li= link_to 'Sign in', new_user_session_url

app/views/app/welcome.html.haml
= turbo_frame_tag :photo_upload, src: new_photo_url
= turbo_frame_tag :my_photos, src: photos_url(user: current_user.id), target: "_top"

app/views/layouts/app.html.haml
%link(href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet")

%header
  %nav
    .nav-wrapper
      = link_to home_url, class: "brand-logo" do
        %span.material-icons camera_alt
        Picabo
      %ul#nav-mobile.right.hide-on-small-only
        = render "app/nav-links"

%ul#slide-out.sidenav
  = render "app/nav-links"

.fixed-action-btn.hide-on-med-and-up
  %a.btn-floating.btn-large.red.sidenav-trigger(data-target="slide-out" href="#")
    %i.large.material-icons menu

%main.container
  = yield

%footer

= javascript_include_tag "app"
= render "app/flash"

app/views/photos/_photo.html.haml
.col.m6.l4.xl3
  .card.hoverable.z-depth-1
    .card-image
      = link_to photo_url(photo) do
        = image_tag photo.representation(resize_to_fill: [500, 500]), loading: :lazy

app/views/photos/create.turbo_stream.haml
= turbo_stream.update "photos" do
  = render collection: current_user.photos.order(created_at: :desc), partial: "photo"

app/views/photos/index.html.haml
= turbo_frame_tag :my_photos, target: "_top" do
  %ul#photos.row
    - if @photos.any?
      = render collection: @photos, partial: "photo"
    - else
      .centered.grey-text No photos yet.

app/views/photos/new.html.haml
= turbo_frame_tag :photo_upload do
  .row
    .col.s12
      .card.my-4
        .card-content(x-data="{uploads: [], ready: false, finished: false}")
          = form_with url: photos_url, method: :post, data: { turbo_frame: "_top" }, html: {"x-on:direct-uploads:end" => "finished = true"} do |form|
            .file-field.input-field
              .btn(x-bind:disabled="uploads.length > 0")
                %span Select photos
                = form.file_field :photo, multiple: true, direct_upload: true, accept: "image/png,image/gif,image/jpeg",
                  "x-on:direct-upload:initialize" => "uploads.push($event.detail)",
                  "x-on:direct-upload:progress" => "uploads.find(u => u.id == $event.detail.id).progress = $event.detail.progress",
                  "x-on:direct-upload:end" => "uploads.find(u => u.id == $event.detail.id).progress = 100",
                  "x-on:change" => "ready = true"

              .file-path-wrapper
                %input.file-path.validate(type="text" placeholder="You can also drap and drop photos here.")

            .center-align
              %button.btn-large(type="submit" x-bind:disabled="uploads.length > 0 || !ready")
                %i.material-icons.left add_to_photos
                Upload

          %template(x-for="upload in uploads")
            .file-progress
              .progress
                .determinate(x-bind:style="`width: ${upload.progress || 0}%`")
              %span(x-text="upload.file.name")

          .all-done(x-show="finished" style="margin-top: 2rem;")
            %b Done!
            Do you want to upload more photos?
            = link_to "OK", new_photo_url, class: "btn"

app/views/photos/show.html.haml
.card.my-4
  .card-image
    = image_tag @photo, class: "materialboxed"
    %span.card-title= @photo.blob.filename
  .card-action
    = link_to rails_blob_path(@photo, disposition: 'attachment'), class: "btn waves-effect waves-light" do
      %i.material-icons.left download
      Download
      %small= number_to_human_size @photo.byte_size

    - if @photo.record_id == current_user.id
      = button_to photo_path(params[:id]), method: :delete, class: "btn-flat waves-effect waves-light" do
        %i.material-icons.left delete
        Delete

app/views/users/_user.html.haml
= link_to user, class: "collection-item" do
  = Initials.svg(user.first_name.presence || user.email, colors: 12, shape: :rect, size: 100)
  %span.badge
    = user.photos.count
    photos

app/views/users/index.html.haml
%h3 Photos by other users

.collection
  = render collection: @users, partial: "user"

app/views/users/show.html.haml
%h3
  Photos by
  = @user.first_name || "#{@user.email[0]}."

= turbo_frame_tag :my_photos, src: photos_url(user: @user), target: "_top"